/* The following code was generated by JFlex 1.4.3 on 31/5/25, 15:06 */

package codigo;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/5/25, 15:06 from the specification file
 * <tt>C:/Users/marvi/Desktop/Marvin pc/Uni General/Septimo Semestre/Compiladores/Proyecto1/JavaApplication1 2/src/codigo/LexerCup.flex</tt>
 */
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  8,  0,  0,  5,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     6, 49,  9,  0,  0,  0,  0,  0, 52, 53,  3, 50,  4, 51,  0,  7, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 56, 47, 48, 47,  0, 
     0, 44,  1, 29,  1, 34, 31,  1, 39, 27,  1,  1, 33, 36, 28, 30, 
    37,  1, 35, 42, 46, 43, 32,  1, 45,  1,  1,  0,  0,  0,  0, 40, 
     0, 16, 10, 14, 23, 13, 22, 21, 15, 26,  1,  1, 18, 41, 20, 19, 
    38,  1, 17, 25, 12, 24,  1,  1,  1, 11,  1, 54,  0, 55,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\23\2\1\10\1\11\1\1\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\5\1\0\1\21\24\2\1\22"+
    "\1\2\1\23\1\10\1\24\10\2\1\25\4\2\1\26"+
    "\1\27\10\2\1\30\1\31\4\2\1\32\1\2\1\33"+
    "\6\2\1\34\11\2\1\35\1\36\1\37\2\2\1\40"+
    "\11\2\1\41\1\2\1\42\1\43\2\2\1\44\1\45"+
    "\4\2\1\46\1\2\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\71\0\344\0\u011d\0\u0156"+
    "\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e"+
    "\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u05ca\0\u05ca\0\u0603\0\u063c"+
    "\0\71\0\71\0\71\0\71\0\71\0\u0675\0\u0156\0\71"+
    "\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d"+
    "\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\162\0\u0b22\0\u0b5b\0\71"+
    "\0\71\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea"+
    "\0\u0d23\0\162\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\162\0\162"+
    "\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf"+
    "\0\162\0\162\0\u1008\0\u1041\0\u107a\0\u10b3\0\162\0\u10ec"+
    "\0\162\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209\0\u1242\0\162"+
    "\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398\0\u13d1\0\u140a"+
    "\0\u1443\0\162\0\162\0\162\0\u147c\0\u14b5\0\162\0\u14ee"+
    "\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6"+
    "\0\162\0\u16ef\0\162\0\162\0\u1728\0\u1761\0\162\0\162"+
    "\0\u179a\0\u17d3\0\u180c\0\u1845\0\162\0\u187e\0\162";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\2\6\1\7\1\6"+
    "\1\10\1\11\1\3\1\12\1\3\1\13\3\3\1\14"+
    "\3\3\1\15\1\16\1\3\1\17\1\20\1\21\1\22"+
    "\2\3\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\3\1\32\2\3\1\33\4\3\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\72\0"+
    "\2\3\7\0\45\3\14\0\1\4\73\0\2\6\1\0"+
    "\1\6\67\0\1\46\62\0\4\47\1\0\2\47\1\0"+
    "\1\50\45\47\3\0\6\47\2\0\2\3\7\0\1\3"+
    "\1\51\43\3\13\0\2\3\7\0\7\3\1\52\35\3"+
    "\13\0\2\3\7\0\5\3\1\53\37\3\13\0\2\3"+
    "\7\0\11\3\1\54\33\3\13\0\2\3\7\0\6\3"+
    "\1\55\1\3\1\56\34\3\13\0\2\3\7\0\11\3"+
    "\1\57\33\3\13\0\2\3\7\0\2\3\1\60\42\3"+
    "\13\0\2\3\7\0\12\3\1\61\32\3\13\0\2\3"+
    "\7\0\22\3\1\62\7\3\1\63\12\3\13\0\2\3"+
    "\7\0\41\3\1\64\3\3\13\0\2\3\7\0\20\3"+
    "\1\65\1\66\23\3\13\0\2\3\7\0\6\3\1\67"+
    "\36\3\13\0\2\3\7\0\30\3\1\70\14\3\13\0"+
    "\2\3\7\0\12\3\1\71\32\3\13\0\2\3\7\0"+
    "\3\3\1\72\41\3\13\0\2\3\7\0\20\3\1\73"+
    "\21\3\1\74\2\3\13\0\2\3\7\0\21\3\1\75"+
    "\23\3\13\0\2\3\7\0\6\3\1\76\36\3\13\0"+
    "\2\3\7\0\20\3\1\77\24\3\72\0\1\100\72\0"+
    "\1\101\10\0\1\4\60\0\1\101\5\0\10\46\1\0"+
    "\60\46\1\0\2\3\7\0\2\3\1\102\42\3\13\0"+
    "\2\3\7\0\16\3\1\103\26\3\13\0\2\3\7\0"+
    "\6\3\1\104\36\3\13\0\2\3\7\0\12\3\1\105"+
    "\32\3\13\0\2\3\7\0\10\3\1\106\34\3\13\0"+
    "\2\3\7\0\11\3\1\107\33\3\13\0\2\3\7\0"+
    "\16\3\1\110\26\3\13\0\2\3\7\0\7\3\1\111"+
    "\35\3\13\0\2\3\7\0\2\3\1\112\42\3\13\0"+
    "\2\3\7\0\21\3\1\113\23\3\13\0\2\3\7\0"+
    "\33\3\1\114\11\3\13\0\2\3\7\0\27\3\1\115"+
    "\15\3\13\0\2\3\7\0\12\3\1\116\32\3\13\0"+
    "\2\3\7\0\22\3\1\117\22\3\13\0\2\3\7\0"+
    "\7\3\1\120\35\3\13\0\2\3\7\0\30\3\1\121"+
    "\14\3\13\0\2\3\7\0\2\3\1\122\42\3\13\0"+
    "\2\3\7\0\34\3\1\123\10\3\13\0\2\3\7\0"+
    "\3\3\1\124\41\3\13\0\2\3\7\0\43\3\1\125"+
    "\1\3\13\0\2\3\7\0\4\3\1\126\12\3\1\127"+
    "\25\3\13\0\2\3\7\0\12\3\1\130\32\3\13\0"+
    "\2\3\7\0\3\3\1\131\41\3\13\0\2\3\7\0"+
    "\3\3\1\132\41\3\13\0\2\3\7\0\7\3\1\131"+
    "\35\3\13\0\2\3\7\0\13\3\1\131\31\3\13\0"+
    "\2\3\7\0\17\3\1\103\25\3\13\0\2\3\7\0"+
    "\6\3\1\133\36\3\13\0\2\3\7\0\1\134\44\3"+
    "\13\0\2\3\7\0\20\3\1\54\24\3\13\0\2\3"+
    "\7\0\23\3\1\135\21\3\13\0\2\3\7\0\31\3"+
    "\1\136\13\3\13\0\2\3\7\0\27\3\1\137\15\3"+
    "\13\0\2\3\7\0\36\3\1\140\6\3\13\0\2\3"+
    "\7\0\31\3\1\141\13\3\13\0\2\3\7\0\11\3"+
    "\1\142\33\3\13\0\2\3\7\0\3\3\1\143\41\3"+
    "\13\0\2\3\7\0\12\3\1\144\32\3\13\0\2\3"+
    "\7\0\36\3\1\145\6\3\13\0\2\3\7\0\3\3"+
    "\1\146\41\3\13\0\2\3\7\0\2\3\1\147\42\3"+
    "\13\0\2\3\7\0\11\3\1\150\33\3\13\0\2\3"+
    "\7\0\2\3\1\131\42\3\13\0\2\3\7\0\10\3"+
    "\1\102\34\3\13\0\2\3\7\0\21\3\1\151\23\3"+
    "\13\0\2\3\7\0\21\3\1\152\23\3\13\0\2\3"+
    "\7\0\7\3\1\153\7\3\1\154\17\3\1\155\5\3"+
    "\13\0\2\3\7\0\12\3\1\156\32\3\13\0\2\3"+
    "\7\0\2\3\1\157\42\3\13\0\2\3\7\0\2\3"+
    "\1\160\42\3\13\0\2\3\7\0\21\3\1\161\23\3"+
    "\13\0\2\3\7\0\7\3\1\162\35\3\13\0\2\3"+
    "\7\0\6\3\1\163\36\3\13\0\2\3\7\0\24\3"+
    "\1\164\20\3\13\0\2\3\7\0\32\3\1\165\12\3"+
    "\13\0\2\3\7\0\3\3\1\166\41\3\13\0\2\3"+
    "\7\0\20\3\1\167\24\3\13\0\2\3\7\0\20\3"+
    "\1\170\24\3\13\0\2\3\7\0\4\3\1\171\40\3"+
    "\13\0\2\3\7\0\20\3\1\172\24\3\13\0\2\3"+
    "\7\0\7\3\1\173\35\3\13\0\2\3\7\0\22\3"+
    "\1\174\22\3\13\0\2\3\7\0\21\3\1\175\23\3"+
    "\13\0\2\3\7\0\34\3\1\176\10\3\13\0\2\3"+
    "\7\0\3\3\1\177\41\3\13\0\2\3\7\0\3\3"+
    "\1\200\41\3\13\0\2\3\7\0\7\3\1\201\35\3"+
    "\13\0\2\3\7\0\6\3\1\202\36\3\13\0\2\3"+
    "\7\0\44\3\1\203\13\0\2\3\7\0\31\3\1\204"+
    "\13\3\13\0\2\3\7\0\3\3\1\205\41\3\13\0"+
    "\2\3\7\0\12\3\1\206\32\3\13\0\2\3\7\0"+
    "\17\3\1\207\25\3\13\0\2\3\7\0\17\3\1\210"+
    "\25\3\13\0\2\3\7\0\2\3\1\211\42\3\13\0"+
    "\2\3\7\0\2\3\1\212\42\3\13\0\2\3\7\0"+
    "\20\3\1\213\24\3\13\0\2\3\7\0\7\3\1\214"+
    "\35\3\13\0\2\3\7\0\7\3\1\215\35\3\13\0"+
    "\2\3\7\0\6\3\1\216\36\3\13\0\2\3\7\0"+
    "\17\3\1\217\25\3\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6327];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\33\1\5\11\1\1\1\0"+
    "\1\11\27\1\2\11\116\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { return new Symbol(sym.LEER, yychar, yyline, yytext());
          }
        case 40: break;
        case 14: 
          { return new Symbol(sym.Llave_a, yychar, yyline, yytext());
          }
        case 41: break;
        case 17: 
          { return new Symbol(sym.Cadena, yychar, yyline, yytext());
          }
        case 42: break;
        case 26: 
          { return new Symbol(sym.NULL, yychar, yyline, yytext());
          }
        case 43: break;
        case 21: 
          { return new Symbol(sym.Int, yychar, yyline, yytext());
          }
        case 44: break;
        case 18: 
          { return new Symbol(sym.PI, yychar, yyline, yytext());
          }
        case 45: break;
        case 6: 
          { return new Symbol(sym.Division, yychar, yyline, yytext());
          }
        case 46: break;
        case 32: 
          { return new Symbol(sym.Fin_si, yychar, yyline, yytext());
          }
        case 47: break;
        case 35: 
          { return new Symbol(sym.IMPRIMIR, yychar, yyline, yytext());
          }
        case 48: break;
        case 38: 
          { return new Symbol(sym.Fin_repetir, yychar, yyline, yytext());
          }
        case 49: break;
        case 33: 
          { return new Symbol(sym.Repetir, yychar, yyline, yytext());
          }
        case 50: break;
        case 19: 
          { return new Symbol(sym.Si, yychar, yyline, yytext());
          }
        case 51: break;
        case 39: 
          { return new Symbol(sym.Fin_mientras, yychar, yyline, yytext());
          }
        case 52: break;
        case 7: 
          { return new Symbol(sym.Comillas, yychar, yyline, yytext());
          }
        case 53: break;
        case 29: 
          { return new Symbol(sym.Hacer, yychar, yyline, yytext());
          }
        case 54: break;
        case 24: 
          { return new Symbol(sym.T_dato, yychar, yyline, yytext());
          }
        case 55: break;
        case 12: 
          { return new Symbol(sym.Parentesis_a, yychar, yyline, yytext());
          }
        case 56: break;
        case 11: 
          { return new Symbol(sym.Resta, yychar, yyline, yytext());
          }
        case 57: break;
        case 31: 
          { return new Symbol(sym.INICIO, yychar, yyline, yytext());
          }
        case 58: break;
        case 15: 
          { return new Symbol(sym.Llave_c, yychar, yyline, yytext());
          }
        case 59: break;
        case 30: 
          { return new Symbol(sym.Hasta, yychar, yyline, yytext());
          }
        case 60: break;
        case 23: 
          { return new Symbol(sym.Var, yychar, yyline, yytext());
          }
        case 61: break;
        case 34: 
          { return new Symbol(sym.MAX_INT, yychar, yyline, yytext());
          }
        case 62: break;
        case 37: 
          { return new Symbol(sym.Mientras, yychar, yyline, yytext());
          }
        case 63: break;
        case 20: 
          { return new Symbol(sym.Op_incremento, yychar, yyline, yytext());
          }
        case 64: break;
        case 13: 
          { return new Symbol(sym.Parentesis_c, yychar, yyline, yytext());
          }
        case 65: break;
        case 16: 
          { return new Symbol(sym.P_coma, yychar, yyline, yytext());
          }
        case 66: break;
        case 2: 
          { String lex = yytext();
    String lower = lex.toLowerCase();

    if (lower.contains("ll") || lower.contains("rr")) {
        return new Symbol(sym.ERROR, yychar, yyline, lex);
    }
    return new Symbol(sym.Identificador, yychar, yyline, lex);
          }
        case 67: break;
        case 36: 
          { return new Symbol(sym.Entonces, yychar, yyline, yytext());
          }
        case 68: break;
        case 4: 
          { return new Symbol(sym.Multiplicacion, yychar, yyline, yytext());
          }
        case 69: break;
        case 10: 
          { return new Symbol(sym.Suma, yychar, yyline, yytext());
          }
        case 70: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 71: break;
        case 22: 
          { return new Symbol(sym.FIN, yychar, yyline, yytext());
          }
        case 72: break;
        case 5: 
          { /*Ignore*/
          }
        case 73: break;
        case 9: 
          { return new Symbol(sym.Igual, yychar, yyline, yytext());
          }
        case 74: break;
        case 3: 
          { return new Symbol(sym.Numero, yychar, yyline, yytext());
          }
        case 75: break;
        case 8: 
          { return new Symbol(sym.Op_relacional, yychar, yyline, yytext());
          }
        case 76: break;
        case 28: 
          { return new Symbol(sym.Sino, yychar, yyline, yytext());
          }
        case 77: break;
        case 25: 
          { return new Symbol(sym.Op_booleano, yychar, yyline, yytext());
          }
        case 78: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
