
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 31 15:06:49 CST 2025
//----------------------------------------------------

package codigo;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat May 31 15:06:49 CST 2025
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\060\000\002\002\004\000\002\026\002\000\002\002" +
    "\006\000\002\003\002\000\002\003\004\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\004\003\000\002\004\003\000\002\005\005\000\002\005" +
    "\007\000\002\006\005\000\002\006\007\000\002\007\006" +
    "\000\002\010\007\000\002\011\007\000\002\012\013\000" +
    "\002\013\015\000\002\024\005\000\002\024\003\000\002" +
    "\024\007\000\002\014\010\000\002\023\003\000\002\015" +
    "\014\000\002\016\005\000\002\016\005\000\002\016\003" +
    "\000\002\017\005\000\002\017\005\000\002\017\003\000" +
    "\002\020\005\000\002\020\003\000\002\020\003\000\002" +
    "\020\003\000\002\021\003\000\002\021\003\000\002\021" +
    "\003\000\002\021\003\000\002\022\004\000\002\022\004" +
    "\000\002\025\002\000\002\025\004\000\002\025\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\004\010\005\001\002\000\004\002\157\001" +
    "\002\000\024\006\000\011\000\012\000\013\000\014\000" +
    "\015\000\021\000\023\000\047\000\001\002\000\024\006" +
    "\ufffe\011\ufffe\012\ufffe\013\ufffe\014\ufffe\015\ufffe\021\ufffe" +
    "\023\ufffe\047\ufffe\001\002\000\024\006\021\011\031\012" +
    "\011\013\013\014\017\015\026\021\016\023\010\047\020" +
    "\001\002\000\004\042\144\001\002\000\004\047\137\001" +
    "\002\000\034\006\ufff5\011\ufff5\012\ufff5\013\ufff5\014\ufff5" +
    "\015\ufff5\020\ufff5\021\ufff5\022\ufff5\023\ufff5\025\ufff5\026" +
    "\ufff5\047\ufff5\001\002\000\004\042\133\001\002\000\026" +
    "\006\ufffd\011\ufffd\012\ufffd\013\ufffd\014\ufffd\015\ufffd\021" +
    "\ufffd\022\ufffd\023\ufffd\047\ufffd\001\002\000\034\006\ufffc" +
    "\011\ufffc\012\ufffc\013\ufffc\014\ufffc\015\ufffc\020\ufffc\021" +
    "\ufffc\022\ufffc\023\ufffc\025\ufffc\026\ufffc\047\ufffc\001\002" +
    "\000\004\042\114\001\002\000\004\042\100\001\002\000" +
    "\004\035\075\001\002\000\004\047\070\001\002\000\034" +
    "\006\ufff7\011\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7\020" +
    "\ufff7\021\ufff7\022\ufff7\023\ufff7\025\ufff7\026\ufff7\047\ufff7" +
    "\001\002\000\034\006\ufff6\011\ufff6\012\ufff6\013\ufff6\014" +
    "\ufff6\015\ufff6\020\ufff6\021\ufff6\022\ufff6\023\ufff6\025\ufff6" +
    "\026\ufff6\047\ufff6\001\002\000\034\006\ufff4\011\ufff4\012" +
    "\ufff4\013\ufff4\014\ufff4\015\ufff4\020\ufff4\021\ufff4\022\ufff4" +
    "\023\ufff4\025\ufff4\026\ufff4\047\ufff4\001\002\000\034\006" +
    "\ufffa\011\ufffa\012\ufffa\013\ufffa\014\ufffa\015\ufffa\020\ufffa" +
    "\021\ufffa\022\ufffa\023\ufffa\025\ufffa\026\ufffa\047\ufffa\001" +
    "\002\000\004\006\033\001\002\000\034\006\ufffb\011\ufffb" +
    "\012\ufffb\013\ufffb\014\ufffb\015\ufffb\020\ufffb\021\ufffb\022" +
    "\ufffb\023\ufffb\025\ufffb\026\ufffb\047\ufffb\001\002\000\034" +
    "\006\ufff9\011\ufff9\012\ufff9\013\ufff9\014\ufff9\015\ufff9\020" +
    "\ufff9\021\ufff9\022\ufff9\023\ufff9\025\ufff9\026\ufff9\047\ufff9" +
    "\001\002\000\004\002\uffff\001\002\000\034\006\ufff8\011" +
    "\ufff8\012\ufff8\013\ufff8\014\ufff8\015\ufff8\020\ufff8\021\ufff8" +
    "\022\ufff8\023\ufff8\025\ufff8\026\ufff8\047\ufff8\001\002\000" +
    "\004\047\034\001\002\000\004\035\035\001\002\000\020" +
    "\027\040\030\042\031\050\032\037\042\041\047\044\050" +
    "\046\001\002\000\044\007\uffdb\016\uffdb\017\uffdb\027\uffdb" +
    "\030\uffdb\031\uffdb\032\uffdb\033\uffdb\036\uffdb\037\uffdb\040" +
    "\uffdb\041\uffdb\042\uffdb\043\uffdb\046\uffdb\047\uffdb\050\uffdb" +
    "\001\002\000\044\007\uffd8\016\uffd8\017\uffd8\027\uffd8\030" +
    "\uffd8\031\uffd8\032\uffd8\033\uffd8\036\uffd8\037\uffd8\040\uffd8" +
    "\041\uffd8\042\uffd8\043\uffd8\046\uffd8\047\uffd8\050\uffd8\001" +
    "\002\000\044\007\uffd7\016\uffd7\017\uffd7\027\uffd7\030\uffd7" +
    "\031\uffd7\032\uffd7\033\uffd7\036\uffd7\037\uffd7\040\uffd7\041" +
    "\uffd7\042\uffd7\043\uffd7\046\uffd7\047\uffd7\050\uffd7\001\002" +
    "\000\020\027\040\030\042\031\050\032\037\042\041\047" +
    "\044\050\046\001\002\000\044\007\uffda\016\uffda\017\uffda" +
    "\027\uffda\030\uffda\031\uffda\032\uffda\033\uffda\036\uffda\037" +
    "\uffda\040\uffda\041\uffda\042\uffda\043\uffda\046\uffda\047\uffda" +
    "\050\uffda\001\002\000\044\007\uffdf\016\uffdf\017\uffdf\027" +
    "\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf\036\uffdf\037\uffdf" +
    "\040\uffdf\041\uffdf\042\uffdf\043\uffdf\046\uffdf\047\uffdf\050" +
    "\uffdf\001\002\000\044\007\uffdc\016\uffdc\017\uffdc\027\uffdc" +
    "\030\uffdc\031\uffdc\032\uffdc\033\uffdc\036\uffdc\037\uffdc\040" +
    "\uffdc\041\uffdc\042\uffdc\043\uffdc\046\uffdc\047\uffdc\050\uffdc" +
    "\001\002\000\044\007\uffe2\016\uffe2\017\uffe2\027\uffe2\030" +
    "\uffe2\031\uffe2\032\uffe2\033\uffe2\036\uffe2\037\uffe2\040\056" +
    "\041\055\042\uffe2\043\uffe2\046\uffe2\047\uffe2\050\uffe2\001" +
    "\002\000\044\007\uffdd\016\uffdd\017\uffdd\027\uffdd\030\uffdd" +
    "\031\uffdd\032\uffdd\033\uffdd\036\uffdd\037\uffdd\040\uffdd\041" +
    "\uffdd\042\uffdd\043\uffdd\046\uffdd\047\uffdd\050\uffdd\001\002" +
    "\000\010\016\051\036\053\037\052\001\002\000\044\007" +
    "\uffd9\016\uffd9\017\uffd9\027\uffd9\030\uffd9\031\uffd9\032\uffd9" +
    "\033\uffd9\036\uffd9\037\uffd9\040\uffd9\041\uffd9\042\uffd9\043" +
    "\uffd9\046\uffd9\047\uffd9\050\uffd9\001\002\000\020\027\040" +
    "\030\042\031\050\032\037\042\041\047\044\050\046\001" +
    "\002\000\020\027\040\030\042\031\050\032\037\042\041" +
    "\047\044\050\046\001\002\000\020\027\040\030\042\031" +
    "\050\032\037\042\041\047\044\050\046\001\002\000\044" +
    "\007\uffe4\016\uffe4\017\uffe4\027\uffe4\030\uffe4\031\uffe4\032" +
    "\uffe4\033\uffe4\036\uffe4\037\uffe4\040\056\041\055\042\uffe4" +
    "\043\uffe4\046\uffe4\047\uffe4\050\uffe4\001\002\000\020\027" +
    "\040\030\042\031\050\032\037\042\041\047\044\050\046" +
    "\001\002\000\020\027\040\030\042\031\050\032\037\042" +
    "\041\047\044\050\046\001\002\000\044\007\uffe1\016\uffe1" +
    "\017\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\033\uffe1\036" +
    "\uffe1\037\uffe1\040\uffe1\041\uffe1\042\uffe1\043\uffe1\046\uffe1" +
    "\047\uffe1\050\uffe1\001\002\000\044\007\uffe0\016\uffe0\017" +
    "\uffe0\027\uffe0\030\uffe0\031\uffe0\032\uffe0\033\uffe0\036\uffe0" +
    "\037\uffe0\040\uffe0\041\uffe0\042\uffe0\043\uffe0\046\uffe0\047" +
    "\uffe0\050\uffe0\001\002\000\044\007\uffe3\016\uffe3\017\uffe3" +
    "\027\uffe3\030\uffe3\031\uffe3\032\uffe3\033\uffe3\036\uffe3\037" +
    "\uffe3\040\056\041\055\042\uffe3\043\uffe3\046\uffe3\047\uffe3" +
    "\050\uffe3\001\002\000\010\017\063\036\053\037\052\001" +
    "\002\000\022\006\021\012\011\013\013\014\017\015\026" +
    "\021\016\023\010\047\020\001\002\000\004\020\065\001" +
    "\002\000\034\006\uffe5\011\uffe5\012\uffe5\013\uffe5\014\uffe5" +
    "\015\uffe5\020\uffe5\021\uffe5\022\uffe5\023\uffe5\025\uffe5\026" +
    "\uffe5\047\uffe5\001\002\000\010\036\053\037\052\043\067" +
    "\001\002\000\044\007\uffde\016\uffde\017\uffde\027\uffde\030" +
    "\uffde\031\uffde\032\uffde\033\uffde\036\uffde\037\uffde\040\uffde" +
    "\041\uffde\042\uffde\043\uffde\046\uffde\047\uffde\050\uffde\001" +
    "\002\000\006\035\072\046\071\001\002\000\034\006\ufff3" +
    "\011\ufff3\012\ufff3\013\ufff3\014\ufff3\015\ufff3\020\ufff3\021" +
    "\ufff3\022\ufff3\023\ufff3\025\ufff3\026\ufff3\047\ufff3\001\002" +
    "\000\020\027\040\030\042\031\050\032\037\042\041\047" +
    "\044\050\046\001\002\000\010\036\053\037\052\046\074" +
    "\001\002\000\034\006\ufff2\011\ufff2\012\ufff2\013\ufff2\014" +
    "\ufff2\015\ufff2\020\ufff2\021\ufff2\022\ufff2\023\ufff2\025\ufff2" +
    "\026\ufff2\047\ufff2\001\002\000\020\027\040\030\042\031" +
    "\050\032\037\042\041\047\044\050\046\001\002\000\010" +
    "\036\053\037\052\046\077\001\002\000\034\006\uffef\011" +
    "\uffef\012\uffef\013\uffef\014\uffef\015\uffef\020\uffef\021\uffef" +
    "\022\uffef\023\uffef\025\uffef\026\uffef\047\uffef\001\002\000" +
    "\022\007\102\027\040\030\042\031\050\032\037\042\041" +
    "\047\044\050\046\001\002\000\004\043\112\001\002\000" +
    "\024\007\104\027\040\030\042\031\050\032\037\042\041" +
    "\043\uffd4\047\044\050\046\001\002\000\030\007\104\027" +
    "\040\030\042\031\050\032\037\036\053\037\052\042\041" +
    "\043\uffd4\047\044\050\046\001\002\000\024\007\104\027" +
    "\040\030\042\031\050\032\037\042\041\043\uffd4\047\044" +
    "\050\046\001\002\000\004\043\uffd6\001\002\000\030\007" +
    "\104\027\040\030\042\031\050\032\037\036\053\037\052" +
    "\042\041\043\uffd4\047\044\050\046\001\002\000\004\043" +
    "\uffd2\001\002\000\004\043\uffd3\001\002\000\004\043\uffd5" +
    "\001\002\000\004\046\113\001\002\000\034\006\uffee\011" +
    "\uffee\012\uffee\013\uffee\014\uffee\015\uffee\020\uffee\021\uffee" +
    "\022\uffee\023\uffee\025\uffee\026\uffee\047\uffee\001\002\000" +
    "\020\027\115\030\042\031\050\032\037\042\116\047\044" +
    "\050\046\001\002\000\016\033\uffd7\036\uffd7\037\uffd7\040" +
    "\uffd7\041\uffd7\043\uffe9\001\002\000\020\027\040\030\042" +
    "\031\050\032\037\042\041\047\044\050\046\001\002\000" +
    "\004\043\123\001\002\000\010\033\121\036\053\037\052" +
    "\001\002\000\020\027\040\030\042\031\050\032\037\042" +
    "\041\047\044\050\046\001\002\000\010\036\053\037\052" +
    "\043\uffea\001\002\000\024\006\ufffe\012\ufffe\013\ufffe\014" +
    "\ufffe\015\ufffe\021\ufffe\022\ufffe\023\ufffe\047\ufffe\001\002" +
    "\000\004\022\126\001\002\000\024\006\021\012\011\013" +
    "\013\014\017\015\026\021\016\022\uffe6\023\010\047\020" +
    "\001\002\000\034\006\uffe7\011\uffe7\012\uffe7\013\uffe7\014" +
    "\uffe7\015\uffe7\020\uffe7\021\uffe7\022\uffe7\023\uffe7\025\uffe7" +
    "\026\uffe7\047\uffe7\001\002\000\012\033\130\036\053\037" +
    "\052\043\067\001\002\000\020\027\040\030\042\031\050" +
    "\032\037\042\041\047\044\050\046\001\002\000\010\036" +
    "\053\037\052\043\132\001\002\000\004\043\uffe8\001\002" +
    "\000\004\047\134\001\002\000\004\043\135\001\002\000" +
    "\004\046\136\001\002\000\034\006\uffed\011\uffed\012\uffed" +
    "\013\uffed\014\uffed\015\uffed\020\uffed\021\uffed\022\uffed\023" +
    "\uffed\025\uffed\026\uffed\047\uffed\001\002\000\006\035\141" +
    "\046\140\001\002\000\034\006\ufff1\011\ufff1\012\ufff1\013" +
    "\ufff1\014\ufff1\015\ufff1\020\ufff1\021\ufff1\022\ufff1\023\ufff1" +
    "\025\ufff1\026\ufff1\047\ufff1\001\002\000\020\027\040\030" +
    "\042\031\050\032\037\042\041\047\044\050\046\001\002" +
    "\000\010\036\053\037\052\046\143\001\002\000\034\006" +
    "\ufff0\011\ufff0\012\ufff0\013\ufff0\014\ufff0\015\ufff0\020\ufff0" +
    "\021\ufff0\022\ufff0\023\ufff0\025\ufff0\026\ufff0\047\ufff0\001" +
    "\002\000\020\027\040\030\042\031\050\032\037\042\041" +
    "\047\044\050\046\001\002\000\010\033\146\036\053\037" +
    "\052\001\002\000\020\027\040\030\042\031\050\032\037" +
    "\042\041\047\044\050\046\001\002\000\010\036\053\037" +
    "\052\043\150\001\002\000\004\024\151\001\002\000\022" +
    "\006\021\012\011\013\013\014\017\015\026\021\016\023" +
    "\010\047\020\001\002\000\006\025\153\026\154\001\002" +
    "\000\022\006\021\012\011\013\013\014\017\015\026\021" +
    "\016\023\010\047\020\001\002\000\034\006\uffec\011\uffec" +
    "\012\uffec\013\uffec\014\uffec\015\uffec\020\uffec\021\uffec\022" +
    "\uffec\023\uffec\025\uffec\026\uffec\047\uffec\001\002\000\004" +
    "\026\156\001\002\000\034\006\uffeb\011\uffeb\012\uffeb\013" +
    "\uffeb\014\uffeb\015\uffeb\020\uffeb\021\uffeb\022\uffeb\023\uffeb" +
    "\025\uffeb\026\uffeb\047\uffeb\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\155\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\026\005\001\001\000\004\003\006\001\001\000\026" +
    "\004\013\005\014\006\026\007\024\010\027\011\031\012" +
    "\021\013\022\014\011\015\023\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\016\046\017\044\020\042\021\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\016\065\017\044\020\042\021\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\016\061\017\044\020\042\021\035\001\001" +
    "\000\010\017\060\020\042\021\035\001\001\000\010\017" +
    "\053\020\042\021\035\001\001\000\002\001\001\000\006" +
    "\020\057\021\035\001\001\000\006\020\056\021\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\004\063\005\014\006\026\007" +
    "\024\010\027\011\031\012\021\013\022\014\011\015\023" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\016\072\017\044\020\042\021\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\016\075\017\044" +
    "\020\042\021\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\016\102\017\044\020\042\021\035\022\100" +
    "\001\001\000\002\001\001\000\014\016\105\017\044\020" +
    "\042\021\035\025\110\001\001\000\014\016\105\017\044" +
    "\020\042\021\035\025\104\001\001\000\014\016\105\017" +
    "\044\020\042\021\035\025\107\001\001\000\002\001\001" +
    "\000\014\016\105\017\044\020\042\021\035\025\106\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\016\117\017" +
    "\044\020\042\021\035\024\116\001\001\000\002\001\001" +
    "\000\012\016\126\017\044\020\042\021\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\016\121\017\044" +
    "\020\042\021\035\001\001\000\002\001\001\000\006\003" +
    "\124\023\123\001\001\000\002\001\001\000\026\004\013" +
    "\005\014\006\026\007\024\010\027\011\031\012\021\013" +
    "\022\014\011\015\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\016\130\017\044\020\042\021\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\016\141\017\044" +
    "\020\042\021\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\016\144\017\044\020\042\021\035\001\001" +
    "\000\002\001\001\000\012\016\146\017\044\020\042\021" +
    "\035\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\004\151\005\014\006\026\007\024\010\027\011\031\012" +
    "\021\013\022\014\011\015\023\001\001\000\002\001\001" +
    "\000\026\004\154\005\014\006\026\007\024\010\027\011" +
    "\031\012\021\013\022\014\011\015\023\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    public void syntax_error(Symbol s) { this.s = s; }
    public Symbol getS()          { return this.s; }

    // —— SEMÁNTICA (atributos de instancia) ——
    public java.util.Map<String,Double> symbolTable = new java.util.HashMap<>();
    public java.util.List<String>    semanticResults = new java.util.ArrayList<>();

    /** Para que la GUI recupere los resultados semánticos */
    public java.util.List<String> getSemanticResults(){
        return semanticResults;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // PRINT_CONCAT_REST ::= EXPRESION PRINT_CONCAT_REST 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int Restleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Restright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object Rest = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
           String valor = ((Double)E).toString();
           RESULT = valor + (String)Rest;
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PRINT_CONCAT_REST",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // PRINT_CONCAT_REST ::= Cadena PRINT_CONCAT_REST 
            {
              Object RESULT =null;
		int Cleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Cright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object C = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int Restleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Restright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object Rest = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
           String texto = ((String)C).substring(1, ((String)C).length() - 1);
           RESULT = texto + (String)Rest;
        
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PRINT_CONCAT_REST",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // PRINT_CONCAT_REST ::= 
            {
              Object RESULT =null;
		 RESULT = ""; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PRINT_CONCAT_REST",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // PRINT_CONCAT ::= Cadena PRINT_CONCAT_REST 
            {
              Object RESULT =null;
		int Cleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Cright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object C = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int Restleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Restright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object Rest = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         String texto = ((String)C).substring(1, ((String)C).length() - 1);
         RESULT = texto + (String)Rest;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PRINT_CONCAT",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // PRINT_CONCAT ::= EXPRESION PRINT_CONCAT_REST 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int Restleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Restright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object Rest = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         String base = ((Double)E).toString();
         RESULT = base + (String)Rest;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PRINT_CONCAT",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // CONSTANTE ::= Op_booleano 
            {
              Object RESULT =null;
		int Bleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Bright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object B = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
    String text = (String) B;
    if ("true".equalsIgnoreCase(text))    RESULT = 1.0;
    else if ("false".equalsIgnoreCase(text)) RESULT = 0.0;
    else throw new RuntimeException("Literal booleano inválido: " + text);
  
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONSTANTE",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // CONSTANTE ::= MAX_INT 
            {
              Object RESULT =null;
		
        RESULT = (double) Integer.MAX_VALUE;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONSTANTE",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // CONSTANTE ::= PI 
            {
              Object RESULT =null;
		
        RESULT = Math.PI;   /* 3.1415926535... */
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONSTANTE",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // CONSTANTE ::= NULL 
            {
              Object RESULT =null;
		
        RESULT = 0.0;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CONSTANTE",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // FACTOR ::= CONSTANTE 
            {
              Object RESULT =null;
		int Cleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Cright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object C = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = (Double) C;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // FACTOR ::= Identificador 
            {
              Object RESULT =null;
		int Ileft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Iright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object I = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         String name = (String) I;
         if (!parser.symbolTable.containsKey(name)) {
             throw new RuntimeException("Variable no declarada: " + name);
         }
         RESULT = parser.symbolTable.get(name);
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // FACTOR ::= Numero 
            {
              Object RESULT =null;
		int Nleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Nright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object N = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = Double.parseDouble((String) N);
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // FACTOR ::= Parentesis_a EXPRESION Parentesis_c 
            {
              Object RESULT =null;
		int Vleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Vright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object V = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
         RESULT = (Double) V;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // TERMINO ::= FACTOR 
            {
              Object RESULT =null;
		int Fleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Fright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object F = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = (Double) F;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // TERMINO ::= TERMINO Division FACTOR 
            {
              Object RESULT =null;
		int E1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int E1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object E1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int Fleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Fright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object F = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = ((Double) E1) / ((Double) F);
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // TERMINO ::= TERMINO Multiplicacion FACTOR 
            {
              Object RESULT =null;
		int E1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int E1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object E1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int Fleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Fright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object F = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = ((Double) E1) * ((Double) F);
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // EXPRESION ::= TERMINO 
            {
              Object RESULT =null;
		int Tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object T = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = (Double) T;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESION ::= EXPRESION Resta TERMINO 
            {
              Object RESULT =null;
		int E1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int E1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object E1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int Tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object T = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = ((Double) E1) - ((Double) T);
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EXPRESION ::= EXPRESION Suma TERMINO 
            {
              Object RESULT =null;
		int E1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int E1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object E1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int Tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object T = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
         RESULT = ((Double) E1) + ((Double) T);
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // REPEAT_LOOP ::= Repetir Int Identificador Igual EXPRESION Hasta EXPRESION Hacer SENTENCIA Fin_repetir 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).value;
		int V1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).left;
		int V1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).right;
		Object V1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).value;
		int V2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int V2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object V2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("REPEAT_LOOP",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-9)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // BLOQUE ::= SENTENCIAS 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("BLOQUE",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // WHILE ::= Mientras Parentesis_a SENTENCIA_BOOLEANA Parentesis_c BLOQUE Fin_mientras 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("WHILE",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // SENTENCIA_BOOLEANA ::= Parentesis_a EXPRESION Op_relacional EXPRESION Parentesis_c 
            {
              Object RESULT =null;
		int E1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int E1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object E1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int E2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int E2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object E2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
          /* Igual que en el primer caso, devolvemos algún valor por consistencia,
             aunque el parser solo use el hecho de que coincida la producción. */
          RESULT = true;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // SENTENCIA_BOOLEANA ::= Op_booleano 
            {
              Object RESULT =null;
		int Bleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int Bright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object B = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
          /* RESULT no es necesario si solo se evalúa la condición en el parser sintáctico.
             Dejarlo en null es suficiente. */
          RESULT = null;
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // SENTENCIA_BOOLEANA ::= EXPRESION Op_relacional EXPRESION 
            {
              Object RESULT =null;
		int E1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int E1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object E1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int E2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int E2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		Object E2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		
          /* Podemos devolver un Booleano si se quisiera utilizar el resultado en Java,
             pero en la gramática lo usamos solo como condición, así que RESULT no se emplea aquí */
          RESULT = true;   /* O simplemente RESULT = null; si no usas el valor */
      
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA_BOOLEANA",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // IF_ELSE ::= Si Parentesis_a EXPRESION Op_relacional EXPRESION Parentesis_c Entonces SENTENCIA Sino SENTENCIA Fin_si 
            {
              Object RESULT =null;
		int V1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)).left;
		int V1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)).right;
		Object V1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)).value;
		int V2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).left;
		int V2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).right;
		Object V2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).value;
		
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF_ELSE",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-10)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // IF ::= Si Parentesis_a EXPRESION Op_relacional EXPRESION Parentesis_c Entonces SENTENCIA Fin_si 
            {
              Object RESULT =null;
		int V1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).left;
		int V1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).right;
		Object V1 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)).value;
		int V2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int V2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		Object V2 = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // READ_STATEMENT ::= LEER Parentesis_a Identificador Parentesis_c P_coma 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("READ_STATEMENT",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // PRINT_STATEMENT ::= IMPRIMIR Parentesis_a PRINT_CONCAT Parentesis_c P_coma 
            {
              Object RESULT =null;
		int Vleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int Vright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		Object V = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		
        parser.semanticResults.add((String)V);
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PRINT_STATEMENT",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ASIGNACION ::= Identificador Igual EXPRESION P_coma 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int Vleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Vright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object V = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        String name = (String) E;
        Double value = (Double) V;
        parser.symbolTable.put(name, value);
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ASIGNACION",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // VAR_DECLARACION ::= Var Identificador Igual EXPRESION P_coma 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int Vleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Vright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object V = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        String name = (String) E;
        Double value = (Double) V;
        parser.symbolTable.put(name, value);
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("VAR_DECLARACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // VAR_DECLARACION ::= Var Identificador P_coma 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        String name = (String) E;
        parser.symbolTable.put(name, 0.0);
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("VAR_DECLARACION",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // DECLARACION ::= Int Identificador Igual EXPRESION P_coma 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int Vleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Vright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object V = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        String name = (String) E;
        Double value = (Double) V;
        parser.symbolTable.put(name, value);
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // DECLARACION ::= Int Identificador P_coma 
            {
              Object RESULT =null;
		int Eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int Eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object E = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
        String name = (String) E;
        parser.symbolTable.put(name, 0.0);
        RESULT = null;
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= REPEAT_LOOP 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= WHILE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= IF_ELSE 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= IF 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= READ_STATEMENT 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= PRINT_STATEMENT 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTENCIA ::= ASIGNACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTENCIA ::= VAR_DECLARACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTENCIA ::= DECLARACION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTENCIAS ::= SENTENCIAS SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // SENTENCIAS ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIAS",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INIT ::= INICIO NT$0 SENTENCIAS FIN 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("INIT",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;

        parser.symbolTable.clear();
        parser.semanticResults.clear();
    
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$0",20, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INIT EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

