
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 31 15:06:49 CST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 25;
  public static final int Llave_c = 35;
  public static final int Op_booleano = 21;
  public static final int Llave_a = 34;
  public static final int PI = 23;
  public static final int IMPRIMIR = 10;
  public static final int T_dato = 3;
  public static final int Var = 8;
  public static final int FIN = 7;
  public static final int Fin_mientras = 16;
  public static final int Repetir = 11;
  public static final int Division = 31;
  public static final int Int = 4;
  public static final int Cadena = 5;
  public static final int Parentesis_c = 33;
  public static final int Parentesis_a = 32;
  public static final int P_coma = 36;
  public static final int Hacer = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NULL = 22;
  public static final int ERROR = 39;
  public static final int Entonces = 18;
  public static final int Identificador = 37;
  public static final int Si = 17;
  public static final int Resta = 29;
  public static final int LEER = 9;
  public static final int MAX_INT = 24;
  public static final int Sino = 19;
  public static final int Mientras = 15;
  public static final int INICIO = 6;
  public static final int Multiplicacion = 30;
  public static final int Fin_si = 20;
  public static final int Op_incremento = 26;
  public static final int Numero = 38;
  public static final int Hasta = 12;
  public static final int Suma = 28;
  public static final int Igual = 27;
  public static final int Fin_repetir = 14;
  public static final int Comillas = 2;
}

